steps:
  - name: docker/compose:1.29.0 # docker-compose
    args:
      - -f
      - class/28-01-deploy-with-docker/backend/docker-compose.prod.yaml
      - build

  - name: docker/compose:1.29.0 # docker-compose
    args:
      - -f
      - class/28-01-deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  - name: gcr.io/cloud-builders/kubectl # kubectl
    args:
      - set
      - image
      - deployment/mybackend
      - my-backend-sha256-1=asia.gcr.io/codecamp-341008/my_backend:1.9
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=mybackend-kubernetes-cluster
