version: '3.3'

services:
  my_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/my_backend/src
    env_file:
      - ./.env

  my_database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myproject'
      MYSQL_ROOT_PASSWORD: '159159'
    ports:
      - 3306:3306

  my_redis:
    image: redis:latest
    ports:
      - 6379:6379
